name: CmdCharger
version: 0.1
description: A Plugin Request
author: Jacklin213

main: me.jacklin213.cmdcharger.CmdCharger

commands:
    cmdcharge:
      description: test
      usage: /cmdcharge setprice [command] [price]
      aliases: cc